[package]
name = "sovereign-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sha2.workspace = true
sovereign-policy = { path = "../sovereign-policy" }
sovereign-state = { path = "../sovereign-state" }

[lints]
workspace = true
